### ISSUE TITLE
RISCV hardware?

### ISSUE THREAD

**Issue by samuk** [blssed/EduRob-LineFollower#1]
Do you think running your line following code is viable on https://openbeagle.org/beaglev-ahead/beaglev-ahead (2ghz, 4gb ram 4tops)

Or does it really need the Jetson?

I'd be running it on this robot hardware https://rosmo-robot.github.io/ which is fairly similar to yours

**Comment by blssed** [comment]
Hey, I think your Hardware should work flawless. You will probably need loads of fine tuning for your Camera etc. but the Jetson is not necessary. The university provided it because we also experimented with neural networks to solve line following, but eventually decided to go for CV.

**Comment by samuk** [comment]
Nice thanks, I'll give it a go sometime
